"""refactor bom to multilevel

Revision ID: 13b276c7702d
Revises: 20260917_01
Create Date: 2026-09-17 14:42:42.124086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '13b276c7702d'
down_revision: Union[str, None] = '20260917_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_category_code'), table_name='product')
    op.drop_index(op.f('ix_product_code'), table_name='product')
    op.drop_table('product')
    op.add_column('bom', sa.Column('parent_material_id', sa.Integer(), nullable=False, comment='父件物料 ID（本 BOM 描述它由哪些子件构成）'))
    op.add_column('bom', sa.Column('bom_type', sa.String(length=16), nullable=False, comment='BOM 类型 DESIGN/MANUFACTURE/SALE'))
    op.alter_column('bom', 'base_qty',
               existing_type=mysql.DECIMAL(precision=12, scale=4),
               comment='基准数量（BOM 行用量对应的产出量）',
               existing_comment='基准数量',
               existing_nullable=False)
    op.alter_column('bom', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=16),
               comment='状态 DRAFT/RELEASED/OBSOLETE',
               existing_comment='状态',
               existing_nullable=False)
    op.drop_index(op.f('ix_bom_product_id'), table_name='bom')
    op.drop_index(op.f('uq_bom_product_version'), table_name='bom')
    op.create_index(op.f('ix_bom_parent_material_id'), 'bom', ['parent_material_id'], unique=False)
    op.create_unique_constraint('uq_bom_parent_version_type', 'bom', ['parent_material_id', 'version', 'bom_type'])
    op.drop_column('bom', 'product_id')
    op.add_column('bom_line', sa.Column('is_phantom', sa.Boolean(), nullable=False, comment='虚拟件：不实际入库，展开时直接穿透到下层子件'))
    op.add_column('bom_line', sa.Column('is_optional', sa.Boolean(), nullable=False, comment='可选件：与同选配组的其它行按配置择一'))
    op.add_column('bom_line', sa.Column('option_group', sa.String(length=32), nullable=True, comment='选配组编码（同组即为同一个可选配置点）'))
    op.add_column('bom_line', sa.Column('substitute_group', sa.String(length=32), nullable=True, comment='替代料组编码（同组内互为替代）'))
    op.add_column('bom_line', sa.Column('substitute_priority', sa.Integer(), nullable=False, comment='替代优先级，数字小者优先选用'))
    op.alter_column('bom_line', 'loss_rate',
               existing_type=mysql.DECIMAL(precision=6, scale=4),
               comment='损耗率（0~1）',
               existing_comment='损耗率',
               existing_nullable=False)
    op.create_index(op.f('ix_bom_line_option_group'), 'bom_line', ['option_group'], unique=False)
    op.create_index(op.f('ix_bom_line_substitute_group'), 'bom_line', ['substitute_group'], unique=False)
    op.alter_column('dictionary_type', 'is_system',
               existing_type=mysql.TINYINT(display_width=1),
               comment='系统内置字典（禁止删除）',
               existing_comment='是否系统内置',
               existing_nullable=False)
    op.alter_column('employee', 'gender',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=8),
               comment='性别 MALE/FEMALE/UNKNOWN',
               existing_comment='性别',
               existing_nullable=False)
    op.add_column('material', sa.Column('model', sa.String(length=64), nullable=True, comment='型号（成品 / 半成品常用）'))
    op.alter_column('material', 'category_code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=32),
               comment='物料分类（引用 dictionary_item.item_code）',
               existing_comment='物料分类',
               existing_nullable=True)
    op.alter_column('material', 'material_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=16),
               comment='物料类型 RAW/SEMI/FINISHED/PACK',
               existing_comment='物料类型',
               existing_nullable=False)
    op.alter_column('material', 'source_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=16),
               comment='来源 PURCHASE/MAKE',
               existing_comment='来源',
               existing_nullable=False)
    op.alter_column('material', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=16),
               comment='状态 ENABLED/DISABLED',
               existing_comment='状态',
               existing_nullable=False)
    op.alter_column('operation_log', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=16),
               comment='结果 SUCCESS/FAIL',
               existing_comment='结果',
               existing_nullable=False)
    op.alter_column('organization', 'path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment='层级路径，形如 /1/3/，用于查子树',
               existing_comment='层级路径',
               existing_nullable=False)
    op.alter_column('organization', 'level',
               existing_type=mysql.INTEGER(),
               comment='层级，从 1 开始',
               existing_comment='层级',
               existing_nullable=False)
    op.alter_column('organization', 'org_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=16),
               comment='类型 COMPANY/DEPT/TEAM',
               existing_comment='组织类型',
               existing_nullable=False)
    op.alter_column('permission', 'perm_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=16),
               comment='类型 MENU/BUTTON/API',
               existing_comment='类型',
               existing_nullable=False)
    op.alter_column('permission', 'path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
               comment='前端路由 / 接口路径',
               existing_comment='路径',
               existing_nullable=True)
    op.alter_column('permission', 'method',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=8),
               comment='HTTP 方法（perm_type=API 时）',
               existing_comment='HTTP 方法',
               existing_nullable=True)
    op.alter_column('role', 'data_scope',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=16),
               comment='访问范围 ALL/ORG/ORG_AND_CHILD/SELF/CUSTOM',
               existing_comment='访问范围',
               existing_nullable=False)
    op.add_column('routing', sa.Column('material_id', sa.Integer(), nullable=False, comment='适用物料 ID'))
    op.alter_column('routing', 'is_default',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否该产品默认工艺路线',
               existing_comment='是否默认',
               existing_nullable=False)
    op.alter_column('routing', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=16),
               comment='状态 DRAFT/RELEASED/OBSOLETE',
               existing_comment='状态',
               existing_nullable=False)
    op.drop_index(op.f('ix_routing_product_id'), table_name='routing')
    op.drop_index(op.f('uq_routing_product_version'), table_name='routing')
    op.create_index(op.f('ix_routing_material_id'), 'routing', ['material_id'], unique=False)
    op.create_unique_constraint('uq_routing_material_version', 'routing', ['material_id', 'version'])
    op.drop_column('routing', 'product_id')
    op.alter_column('routing_step', 'step_no',
               existing_type=mysql.INTEGER(),
               comment='工序号（步序）',
               existing_comment='工序号',
               existing_nullable=False)
    op.alter_column('routing_step', 'setup_minutes',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='准备工时（分钟）',
               existing_comment='准备工时',
               existing_nullable=True)
    op.alter_column('routing_step', 'run_minutes',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='单件工时（分钟）',
               existing_comment='单件工时',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('routing_step', 'run_minutes',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='单件工时',
               existing_comment='单件工时（分钟）',
               existing_nullable=True)
    op.alter_column('routing_step', 'setup_minutes',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               comment='准备工时',
               existing_comment='准备工时（分钟）',
               existing_nullable=True)
    op.alter_column('routing_step', 'step_no',
               existing_type=mysql.INTEGER(),
               comment='工序号',
               existing_comment='工序号（步序）',
               existing_nullable=False)
    op.add_column('routing', sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='适用产品 ID'))
    op.drop_constraint('uq_routing_material_version', 'routing', type_='unique')
    op.drop_index(op.f('ix_routing_material_id'), table_name='routing')
    op.create_index(op.f('uq_routing_product_version'), 'routing', ['product_id', 'version'], unique=True)
    op.create_index(op.f('ix_routing_product_id'), 'routing', ['product_id'], unique=False)
    op.alter_column('routing', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=16),
               comment='状态',
               existing_comment='状态 DRAFT/RELEASED/OBSOLETE',
               existing_nullable=False)
    op.alter_column('routing', 'is_default',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否默认',
               existing_comment='是否该产品默认工艺路线',
               existing_nullable=False)
    op.drop_column('routing', 'material_id')
    op.alter_column('role', 'data_scope',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=16),
               comment='访问范围',
               existing_comment='访问范围 ALL/ORG/ORG_AND_CHILD/SELF/CUSTOM',
               existing_nullable=False)
    op.alter_column('permission', 'method',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=8),
               comment='HTTP 方法',
               existing_comment='HTTP 方法（perm_type=API 时）',
               existing_nullable=True)
    op.alter_column('permission', 'path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=128),
               comment='路径',
               existing_comment='前端路由 / 接口路径',
               existing_nullable=True)
    op.alter_column('permission', 'perm_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=16),
               comment='类型',
               existing_comment='类型 MENU/BUTTON/API',
               existing_nullable=False)
    op.alter_column('organization', 'org_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=16),
               comment='组织类型',
               existing_comment='类型 COMPANY/DEPT/TEAM',
               existing_nullable=False)
    op.alter_column('organization', 'level',
               existing_type=mysql.INTEGER(),
               comment='层级',
               existing_comment='层级，从 1 开始',
               existing_nullable=False)
    op.alter_column('organization', 'path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               comment='层级路径',
               existing_comment='层级路径，形如 /1/3/，用于查子树',
               existing_nullable=False)
    op.alter_column('operation_log', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=16),
               comment='结果',
               existing_comment='结果 SUCCESS/FAIL',
               existing_nullable=False)
    op.alter_column('material', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=16),
               comment='状态',
               existing_comment='状态 ENABLED/DISABLED',
               existing_nullable=False)
    op.alter_column('material', 'source_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=16),
               comment='来源',
               existing_comment='来源 PURCHASE/MAKE',
               existing_nullable=False)
    op.alter_column('material', 'material_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=16),
               comment='物料类型',
               existing_comment='物料类型 RAW/SEMI/FINISHED/PACK',
               existing_nullable=False)
    op.alter_column('material', 'category_code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=32),
               comment='物料分类',
               existing_comment='物料分类（引用 dictionary_item.item_code）',
               existing_nullable=True)
    op.drop_column('material', 'model')
    op.alter_column('employee', 'gender',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=8),
               comment='性别',
               existing_comment='性别 MALE/FEMALE/UNKNOWN',
               existing_nullable=False)
    op.alter_column('dictionary_type', 'is_system',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否系统内置',
               existing_comment='系统内置字典（禁止删除）',
               existing_nullable=False)
    op.drop_index(op.f('ix_bom_line_substitute_group'), table_name='bom_line')
    op.drop_index(op.f('ix_bom_line_option_group'), table_name='bom_line')
    op.alter_column('bom_line', 'loss_rate',
               existing_type=mysql.DECIMAL(precision=6, scale=4),
               comment='损耗率',
               existing_comment='损耗率（0~1）',
               existing_nullable=False)
    op.drop_column('bom_line', 'substitute_priority')
    op.drop_column('bom_line', 'substitute_group')
    op.drop_column('bom_line', 'option_group')
    op.drop_column('bom_line', 'is_optional')
    op.drop_column('bom_line', 'is_phantom')
    op.add_column('bom', sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='所属产品 ID'))
    op.drop_constraint('uq_bom_parent_version_type', 'bom', type_='unique')
    op.drop_index(op.f('ix_bom_parent_material_id'), table_name='bom')
    op.create_index(op.f('uq_bom_product_version'), 'bom', ['product_id', 'version'], unique=True)
    op.create_index(op.f('ix_bom_product_id'), 'bom', ['product_id'], unique=False)
    op.alter_column('bom', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=16),
               comment='状态',
               existing_comment='状态 DRAFT/RELEASED/OBSOLETE',
               existing_nullable=False)
    op.alter_column('bom', 'base_qty',
               existing_type=mysql.DECIMAL(precision=12, scale=4),
               comment='基准数量',
               existing_comment='基准数量（BOM 行用量对应的产出量）',
               existing_nullable=False)
    op.drop_column('bom', 'bom_type')
    op.drop_column('bom', 'parent_material_id')
    op.create_table('product',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(collation='utf8mb4_general_ci', length=32), nullable=False, comment='产品编码'),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=64), nullable=False, comment='产品名称'),
    sa.Column('spec', mysql.VARCHAR(collation='utf8mb4_general_ci', length=128), nullable=True, comment='规格型号'),
    sa.Column('model', mysql.VARCHAR(collation='utf8mb4_general_ci', length=64), nullable=True, comment='产品型号'),
    sa.Column('unit', mysql.VARCHAR(collation='utf8mb4_general_ci', length=16), nullable=False, comment='计量单位'),
    sa.Column('category_code', mysql.VARCHAR(collation='utf8mb4_general_ci', length=32), nullable=True, comment='产品分类'),
    sa.Column('standard_cost', mysql.DECIMAL(precision=12, scale=2), nullable=True, comment='标准成本'),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_general_ci', length=16), nullable=False, comment='状态'),
    sa.Column('remark', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True, comment='备注'),
    sa.Column('created_at', mysql.DATETIME(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_product_code'), 'product', ['code'], unique=True)
    op.create_index(op.f('ix_product_category_code'), 'product', ['category_code'], unique=False)
    # ### end Alembic commands ###
