"""baseline schema for five modules

Revision ID: 9e6fa0de8416
Revises: 
Create Date: 2026-09-19 19:23:15.013887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e6fa0de8416'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pln_mps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('mps_no', sa.String(length=50), nullable=False, comment='MPS编号'),
    sa.Column('mps_name', sa.String(length=100), nullable=True, comment='计划名称'),
    sa.Column('program_no', sa.String(length=50), nullable=True, comment='计划编号/产线'),
    sa.Column('plan_year', sa.Integer(), nullable=False, comment='计划年度'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='计划开始日期'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='计划结束日期'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('DRAFT','CONFIRMED','RELEASED','IN_PROGRESS','COMPLETED','CANCELLED')", name='ck_pln_mps_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mps_no')
    )
    op.create_index(op.f('ix_pln_mps_status'), 'pln_mps', ['status'], unique=False)
    op.create_table('pur_purchase_plan',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('plan_no', sa.String(length=50), nullable=False, comment='采购计划编号'),
    sa.Column('plan_date', sa.Date(), nullable=False, comment='计划日期'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('DRAFT','CONFIRMED','RELEASED','COMPLETED','CANCELLED')", name='ck_pur_purchase_plan_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_no')
    )
    op.create_index(op.f('ix_pur_purchase_plan_status'), 'pur_purchase_plan', ['status'], unique=False)
    op.create_table('pur_supplier',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('supplier_code', sa.String(length=50), nullable=False, comment='供应商编码'),
    sa.Column('supplier_name', sa.String(length=100), nullable=False, comment='供应商名称'),
    sa.Column('contact_person', sa.String(length=50), nullable=True, comment='联系人'),
    sa.Column('phone', sa.String(length=30), nullable=True, comment='联系电话'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('address', sa.String(length=200), nullable=True, comment='地址'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('ACTIVE','INACTIVE')", name='ck_pur_supplier_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_code')
    )
    op.create_table('sal_customer',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('customer_code', sa.String(length=50), nullable=False, comment='客户编码'),
    sa.Column('customer_name', sa.String(length=100), nullable=False, comment='客户名称'),
    sa.Column('contact_person', sa.String(length=50), nullable=True, comment='联系人'),
    sa.Column('phone', sa.String(length=30), nullable=True, comment='联系电话'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('address', sa.String(length=200), nullable=True, comment='地址'),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=2), nullable=False, comment='信用额度'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('ACTIVE','INACTIVE')", name='ck_sal_customer_status'),
    sa.CheckConstraint('credit_limit >= 0', name='ck_sal_customer_credit'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_code')
    )
    op.create_table('sys_dictionary',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dict_code', sa.String(length=50), nullable=False, comment='字典编码'),
    sa.Column('dict_name', sa.String(length=100), nullable=False, comment='字典名称'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('ACTIVE','INACTIVE')", name='ck_sys_dictionary_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dict_code')
    )
    op.create_table('sys_material',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('material_code', sa.String(length=50), nullable=False, comment='物料编码'),
    sa.Column('material_name', sa.String(length=100), nullable=False, comment='物料名称'),
    sa.Column('material_type', sa.String(length=20), nullable=False, comment='物料类型 RAW/PURCHASED/SEMI/FINISHED'),
    sa.Column('supply_type', sa.String(length=20), nullable=False, comment='供应类型 MAKE/BUY'),
    sa.Column('unit_code', sa.String(length=20), nullable=False, comment='计量单位'),
    sa.Column('specification', sa.String(length=200), nullable=True, comment='规格型号'),
    sa.Column('material_group', sa.String(length=50), nullable=True, comment='物料分组'),
    sa.Column('lead_time_days', sa.Integer(), nullable=False, comment='提前期（天）'),
    sa.Column('safety_stock', sa.Numeric(precision=18, scale=4), nullable=False, comment='安全库存'),
    sa.Column('standard_cost', sa.Numeric(precision=18, scale=2), nullable=False, comment='标准成本'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("material_type IN ('RAW','PURCHASED','SEMI','FINISHED')", name='ck_sys_material_type'),
    sa.CheckConstraint("status IN ('ACTIVE','INACTIVE')", name='ck_sys_material_status'),
    sa.CheckConstraint("supply_type IN ('MAKE','BUY')", name='ck_sys_material_supply_type'),
    sa.CheckConstraint('lead_time_days >= 0', name='ck_sys_material_lead_time'),
    sa.CheckConstraint('safety_stock >= 0', name='ck_sys_material_safety_stock'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_code')
    )
    op.create_index(op.f('ix_sys_material_material_type'), 'sys_material', ['material_type'], unique=False)
    op.create_index(op.f('ix_sys_material_supply_type'), 'sys_material', ['supply_type'], unique=False)
    op.create_table('sys_operation_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('module', sa.String(length=20), nullable=False, comment='模块标识'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='动作（CREATE/CONFIRM/...）'),
    sa.Column('target_type', sa.String(length=50), nullable=False, comment='目标对象类型（表名）'),
    sa.Column('target_id', sa.BigInteger(), nullable=True, comment='目标对象ID'),
    sa.Column('operator_id', sa.BigInteger(), nullable=True, comment='操作人ID（sys_user.id）'),
    sa.Column('detail', sa.Text(), nullable=True, comment='详情'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='发生时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sys_operation_log_module'), 'sys_operation_log', ['module'], unique=False)
    op.create_table('sys_organization',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_code', sa.String(length=50), nullable=False, comment='组织编码'),
    sa.Column('org_name', sa.String(length=100), nullable=False, comment='组织名称'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='上级组织ID'),
    sa.Column('org_type', sa.String(length=20), nullable=False, comment='组织类型'),
    sa.Column('manager_id', sa.BigInteger(), nullable=True, comment='负责人ID（sys_personnel.id，延迟引用避免建表循环）'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("org_type IN ('COMPANY','FACTORY','DEPARTMENT','WORKSHOP','WAREHOUSE')", name='ck_sys_organization_type'),
    sa.CheckConstraint("status IN ('ACTIVE','INACTIVE')", name='ck_sys_organization_status'),
    sa.ForeignKeyConstraint(['parent_id'], ['sys_organization.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_code')
    )
    op.create_index(op.f('ix_sys_organization_parent_id'), 'sys_organization', ['parent_id'], unique=False)
    op.create_table('sys_permission',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('perm_code', sa.String(length=50), nullable=False, comment='权限编码'),
    sa.Column('perm_name', sa.String(length=100), nullable=False, comment='权限名称'),
    sa.Column('perm_type', sa.String(length=20), nullable=False, comment='权限类型'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='上级权限ID'),
    sa.Column('path', sa.String(length=200), nullable=True, comment='前端路由/接口路径'),
    sa.Column('module', sa.String(length=20), nullable=True, comment='所属模块'),
    sa.Column('sort_no', sa.Integer(), nullable=False, comment='排序号'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("perm_type IN ('MENU','PAGE','ACTION')", name='ck_sys_permission_type'),
    sa.CheckConstraint("status IN ('ACTIVE','INACTIVE')", name='ck_sys_permission_status'),
    sa.ForeignKeyConstraint(['parent_id'], ['sys_permission.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('perm_code')
    )
    op.create_index(op.f('ix_sys_permission_parent_id'), 'sys_permission', ['parent_id'], unique=False)
    op.create_table('sys_role',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_code', sa.String(length=50), nullable=False, comment='角色编码'),
    sa.Column('role_name', sa.String(length=100), nullable=False, comment='角色名称'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='描述'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('ACTIVE','INACTIVE')", name='ck_sys_role_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_code')
    )
    op.create_table('pln_demand',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('demand_no', sa.String(length=50), nullable=False, comment='需求单号'),
    sa.Column('source_type', sa.String(length=20), nullable=False, comment='需求来源 SALES/STOCKFILL/MPS'),
    sa.Column('source_reference_id', sa.Integer(), nullable=True, comment='来源单据ID（跨模块多态引用）'),
    sa.Column('source_no', sa.String(length=50), nullable=True, comment='来源单号'),
    sa.Column('material_id', sa.BigInteger(), nullable=False, comment='物料ID'),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='需求数量'),
    sa.Column('due_date', sa.Date(), nullable=False, comment='需求日期'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("source_type IN ('SALES','STOCKFILL','MPS')", name='ck_pln_demand_source'),
    sa.CheckConstraint("status IN ('DRAFT','CONFIRMED','RELEASED','COMPLETED','CANCELLED')", name='ck_pln_demand_status'),
    sa.CheckConstraint('quantity > 0', name='ck_pln_demand_qty'),
    sa.ForeignKeyConstraint(['material_id'], ['sys_material.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('demand_no')
    )
    op.create_index(op.f('ix_pln_demand_due_date'), 'pln_demand', ['due_date'], unique=False)
    op.create_index(op.f('ix_pln_demand_material_id'), 'pln_demand', ['material_id'], unique=False)
    op.create_index(op.f('ix_pln_demand_source_reference_id'), 'pln_demand', ['source_reference_id'], unique=False)
    op.create_index(op.f('ix_pln_demand_source_type'), 'pln_demand', ['source_type'], unique=False)
    op.create_index(op.f('ix_pln_demand_status'), 'pln_demand', ['status'], unique=False)
    op.create_table('pln_mps_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('mps_id', sa.BigInteger(), nullable=False, comment='MPS头ID'),
    sa.Column('material_id', sa.BigInteger(), nullable=False, comment='产成品物料ID'),
    sa.Column('period_label', sa.String(length=20), nullable=True, comment='计划期间标签（如 2026-01）'),
    sa.Column('planned_qty', sa.Numeric(precision=18, scale=4), nullable=False, comment='计划生产数量'),
    sa.Column('finished_qty', sa.Numeric(precision=18, scale=4), nullable=False, comment='已完成数量'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='计划开始日期'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='计划完成日期'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('DRAFT','CONFIRMED','RELEASED','IN_PROGRESS','COMPLETED','CANCELLED')", name='ck_pln_mps_item_status'),
    sa.CheckConstraint('finished_qty >= 0', name='ck_pln_mps_item_finished'),
    sa.CheckConstraint('planned_qty > 0', name='ck_pln_mps_item_qty'),
    sa.ForeignKeyConstraint(['material_id'], ['sys_material.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['mps_id'], ['pln_mps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pln_mps_item_material_id'), 'pln_mps_item', ['material_id'], unique=False)
    op.create_index(op.f('ix_pln_mps_item_mps_id'), 'pln_mps_item', ['mps_id'], unique=False)
    op.create_table('pln_mrp_run',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_no', sa.String(length=50), nullable=False, comment='运算批次号'),
    sa.Column('mps_id', sa.BigInteger(), nullable=True, comment='MPS头ID'),
    sa.Column('run_at', sa.DateTime(), nullable=False, comment='运算时间'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('material_count', sa.Integer(), nullable=False, comment='涉及物料数'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('DRAFT','IN_PROGRESS','COMPLETED','CANCELLED')", name='ck_pln_mrp_run_status'),
    sa.ForeignKeyConstraint(['mps_id'], ['pln_mps.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_no')
    )
    op.create_index(op.f('ix_pln_mrp_run_mps_id'), 'pln_mrp_run', ['mps_id'], unique=False)
    op.create_index(op.f('ix_pln_mrp_run_status'), 'pln_mrp_run', ['status'], unique=False)
    op.create_table('pur_purchase_plan_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=False, comment='采购计划头ID'),
    sa.Column('material_id', sa.BigInteger(), nullable=False, comment='物料ID'),
    sa.Column('required_qty', sa.Numeric(precision=18, scale=4), nullable=False, comment='需求数量'),
    sa.Column('ordered_qty', sa.Numeric(precision=18, scale=4), nullable=False, comment='已下单数量'),
    sa.Column('required_date', sa.Date(), nullable=False, comment='需求日期'),
    sa.Column('source_type', sa.String(length=30), nullable=False, comment='来源类型 MRP/REORDER/MANUAL'),
    sa.Column('source_reference_id', sa.Integer(), nullable=True, comment='来源单据ID（多态引用）'),
    sa.Column('supplier_id', sa.BigInteger(), nullable=True, comment='建议供应商ID'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("source_type IN ('MRP','REORDER','MANUAL')", name='ck_pur_plan_item_source'),
    sa.CheckConstraint("status IN ('DRAFT','CONFIRMED','RELEASED','COMPLETED','CANCELLED')", name='ck_pur_plan_item_status'),
    sa.CheckConstraint('ordered_qty >= 0', name='ck_pur_plan_item_ordered'),
    sa.CheckConstraint('required_qty > 0', name='ck_pur_plan_item_qty'),
    sa.ForeignKeyConstraint(['material_id'], ['sys_material.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_id'], ['pur_purchase_plan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['pur_supplier.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pur_purchase_plan_item_material_id'), 'pur_purchase_plan_item', ['material_id'], unique=False)
    op.create_index(op.f('ix_pur_purchase_plan_item_plan_id'), 'pur_purchase_plan_item', ['plan_id'], unique=False)
    op.create_index(op.f('ix_pur_purchase_plan_item_source_reference_id'), 'pur_purchase_plan_item', ['source_reference_id'], unique=False)
    op.create_index(op.f('ix_pur_purchase_plan_item_source_type'), 'pur_purchase_plan_item', ['source_type'], unique=False)
    op.create_table('pur_supplier_material',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.BigInteger(), nullable=False, comment='供应商ID'),
    sa.Column('material_id', sa.BigInteger(), nullable=False, comment='物料ID'),
    sa.Column('is_primary', sa.Boolean(), nullable=False, comment='是否主供应商'),
    sa.Column('supply_price', sa.Numeric(precision=18, scale=2), nullable=False, comment='供货单价'),
    sa.Column('lead_time_days', sa.Integer(), nullable=False, comment='供货提前期（天）'),
    sa.Column('min_order_qty', sa.Numeric(precision=18, scale=4), nullable=False, comment='最小起订量'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint('lead_time_days >= 0', name='ck_pur_supplier_material_lead'),
    sa.CheckConstraint('supply_price >= 0', name='ck_pur_supplier_material_price'),
    sa.ForeignKeyConstraint(['material_id'], ['sys_material.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['pur_supplier.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'material_id', name='uq_pur_supplier_material')
    )
    op.create_index(op.f('ix_pur_supplier_material_material_id'), 'pur_supplier_material', ['material_id'], unique=False)
    op.create_index(op.f('ix_pur_supplier_material_supplier_id'), 'pur_supplier_material', ['supplier_id'], unique=False)
    op.create_table('sal_forecast',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('forecast_no', sa.String(length=50), nullable=False, comment='预测单号'),
    sa.Column('customer_id', sa.BigInteger(), nullable=True, comment='客户ID'),
    sa.Column('material_id', sa.BigInteger(), nullable=False, comment='物料ID'),
    sa.Column('forecast_month', sa.String(length=7), nullable=False, comment='预测月份（YYYY-MM）'),
    sa.Column('forecast_qty', sa.Numeric(precision=18, scale=4), nullable=False, comment='预测数量'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('DRAFT','CONFIRMED','COMPLETED','CANCELLED')", name='ck_sal_forecast_status'),
    sa.CheckConstraint('forecast_qty >= 0', name='ck_sal_forecast_qty'),
    sa.ForeignKeyConstraint(['customer_id'], ['sal_customer.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['material_id'], ['sys_material.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('forecast_no')
    )
    op.create_index(op.f('ix_sal_forecast_customer_id'), 'sal_forecast', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sal_forecast_material_id'), 'sal_forecast', ['material_id'], unique=False)
    op.create_index(op.f('ix_sal_forecast_status'), 'sal_forecast', ['status'], unique=False)
    op.create_table('sys_bom',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('bom_code', sa.String(length=50), nullable=False, comment='BOM编码'),
    sa.Column('material_id', sa.BigInteger(), nullable=False, comment='母件物料ID（sys_material.id）'),
    sa.Column('bom_version', sa.String(length=20), nullable=False, comment='BOM版本'),
    sa.Column('effective_date', sa.Date(), nullable=True, comment='生效日期'),
    sa.Column('expiry_date', sa.Date(), nullable=True, comment='失效日期'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否当前激活版本'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('ACTIVE','INACTIVE')", name='ck_sys_bom_status'),
    sa.ForeignKeyConstraint(['material_id'], ['sys_material.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'bom_version', name='uq_sys_bom_material_version')
    )
    op.create_index(op.f('ix_sys_bom_material_id'), 'sys_bom', ['material_id'], unique=False)
    op.create_table('sys_dictionary_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dict_id', sa.BigInteger(), nullable=False, comment='字典ID'),
    sa.Column('item_code', sa.String(length=50), nullable=False, comment='字典项编码'),
    sa.Column('item_name', sa.String(length=100), nullable=False, comment='字典项名称'),
    sa.Column('item_value', sa.String(length=200), nullable=True, comment='字典项值'),
    sa.Column('sort_no', sa.Integer(), nullable=False, comment='排序号'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('ACTIVE','INACTIVE')", name='ck_sys_dictionary_item_status'),
    sa.ForeignKeyConstraint(['dict_id'], ['sys_dictionary.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dict_id', 'item_code', name='uq_sys_dictionary_item')
    )
    op.create_index(op.f('ix_sys_dictionary_item_dict_id'), 'sys_dictionary_item', ['dict_id'], unique=False)
    op.create_table('sys_personnel',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('employee_no', sa.String(length=50), nullable=False, comment='员工工号'),
    sa.Column('person_name', sa.String(length=100), nullable=False, comment='姓名'),
    sa.Column('org_id', sa.BigInteger(), nullable=False, comment='所属组织ID'),
    sa.Column('position', sa.String(length=50), nullable=True, comment='岗位'),
    sa.Column('phone', sa.String(length=30), nullable=True, comment='联系电话'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('hire_date', sa.Date(), nullable=True, comment='入职日期'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('ACTIVE','INACTIVE')", name='ck_sys_personnel_status'),
    sa.ForeignKeyConstraint(['org_id'], ['sys_organization.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_no')
    )
    op.create_index(op.f('ix_sys_personnel_org_id'), 'sys_personnel', ['org_id'], unique=False)
    op.create_table('sys_role_permission',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.Column('permission_id', sa.BigInteger(), nullable=False, comment='权限ID'),
    sa.ForeignKeyConstraint(['permission_id'], ['sys_permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_sys_role_permission')
    )
    op.create_index(op.f('ix_sys_role_permission_permission_id'), 'sys_role_permission', ['permission_id'], unique=False)
    op.create_index(op.f('ix_sys_role_permission_role_id'), 'sys_role_permission', ['role_id'], unique=False)
    op.create_table('sys_routing',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('routing_code', sa.String(length=50), nullable=False, comment='工艺路线编码'),
    sa.Column('material_id', sa.BigInteger(), nullable=False, comment='自制件物料ID（sys_material.id）'),
    sa.Column('routing_version', sa.String(length=20), nullable=False, comment='工艺版本'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('ACTIVE','INACTIVE')", name='ck_sys_routing_status'),
    sa.ForeignKeyConstraint(['material_id'], ['sys_material.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'routing_version', name='uq_sys_routing_material_version')
    )
    op.create_index(op.f('ix_sys_routing_material_id'), 'sys_routing', ['material_id'], unique=False)
    op.create_table('inv_warehouse',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('warehouse_code', sa.String(length=50), nullable=False, comment='仓库编码'),
    sa.Column('warehouse_name', sa.String(length=100), nullable=False, comment='仓库名称'),
    sa.Column('org_id', sa.BigInteger(), nullable=True, comment='所属组织ID'),
    sa.Column('manager_id', sa.BigInteger(), nullable=True, comment='仓库负责人（sys_personnel.id）'),
    sa.Column('address', sa.String(length=200), nullable=True, comment='地址'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('ACTIVE','INACTIVE')", name='ck_inv_warehouse_status'),
    sa.ForeignKeyConstraint(['manager_id'], ['sys_personnel.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['sys_organization.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_code')
    )
    op.create_index(op.f('ix_inv_warehouse_org_id'), 'inv_warehouse', ['org_id'], unique=False)
    op.create_table('pln_mrp_result',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False, comment='运算批次ID'),
    sa.Column('material_id', sa.BigInteger(), nullable=False, comment='物料ID'),
    sa.Column('parent_material_id', sa.BigInteger(), nullable=True, comment='父件物料ID（BOM 展开时记录来源母件）'),
    sa.Column('bom_level', sa.Integer(), nullable=False, comment='BOM层级（成品=0）'),
    sa.Column('gross_requirement', sa.Numeric(precision=18, scale=4), nullable=False, comment='毛需求'),
    sa.Column('on_hand', sa.Numeric(precision=18, scale=4), nullable=False, comment='库存量（来自 inventory 快照）'),
    sa.Column('available_quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='可用库存（库存 - 锁定量）'),
    sa.Column('safety_stock', sa.Numeric(precision=18, scale=4), nullable=False, comment='安全库存'),
    sa.Column('net_requirement', sa.Numeric(precision=18, scale=4), nullable=False, comment='净需求 = max(毛需求+安全库存-可用库存, 0)'),
    sa.Column('order_qty', sa.Numeric(precision=18, scale=4), nullable=False, comment='建议下达数量'),
    sa.Column('supply_type', sa.String(length=20), nullable=False, comment='供应类型 MAKE/BUY'),
    sa.Column('lead_time_days', sa.Integer(), nullable=False, comment='提前期（天）'),
    sa.Column('requirement_date', sa.Date(), nullable=False, comment='需求日期'),
    sa.Column('planned_release_date', sa.Date(), nullable=True, comment='建议下达日期（需求日期 - 提前期）'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('DRAFT','CONFIRMED','RELEASED','COMPLETED','CANCELLED')", name='ck_pln_mrp_result_status'),
    sa.CheckConstraint("supply_type IN ('MAKE','BUY')", name='ck_pln_mrp_result_supply'),
    sa.CheckConstraint('bom_level >= 0', name='ck_pln_mrp_result_level'),
    sa.CheckConstraint('gross_requirement >= 0', name='ck_pln_mrp_result_gross'),
    sa.CheckConstraint('net_requirement >= 0', name='ck_pln_mrp_result_net'),
    sa.ForeignKeyConstraint(['material_id'], ['sys_material.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_material_id'], ['sys_material.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['pln_mrp_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pln_mrp_result_material_id'), 'pln_mrp_result', ['material_id'], unique=False)
    op.create_index(op.f('ix_pln_mrp_result_parent_material_id'), 'pln_mrp_result', ['parent_material_id'], unique=False)
    op.create_index(op.f('ix_pln_mrp_result_run_id'), 'pln_mrp_result', ['run_id'], unique=False)
    op.create_index(op.f('ix_pln_mrp_result_status'), 'pln_mrp_result', ['status'], unique=False)
    op.create_index(op.f('ix_pln_mrp_result_supply_type'), 'pln_mrp_result', ['supply_type'], unique=False)
    op.create_table('pur_order',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=False, comment='采购订单号'),
    sa.Column('supplier_id', sa.BigInteger(), nullable=False, comment='供应商ID'),
    sa.Column('order_date', sa.Date(), nullable=False, comment='下单日期'),
    sa.Column('expected_date', sa.Date(), nullable=False, comment='预计到货日期'),
    sa.Column('buyer_id', sa.BigInteger(), nullable=True, comment='采购员（sys_personnel.id）'),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False, comment='订单总金额'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('DRAFT','CONFIRMED','RELEASED','IN_PROGRESS','COMPLETED','CANCELLED')", name='ck_pur_order_status'),
    sa.ForeignKeyConstraint(['buyer_id'], ['sys_personnel.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['pur_supplier.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_index(op.f('ix_pur_order_buyer_id'), 'pur_order', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_pur_order_status'), 'pur_order', ['status'], unique=False)
    op.create_index(op.f('ix_pur_order_supplier_id'), 'pur_order', ['supplier_id'], unique=False)
    op.create_table('pur_supplier_evaluation',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.BigInteger(), nullable=False, comment='供应商ID'),
    sa.Column('evaluate_date', sa.Date(), nullable=False, comment='评价日期'),
    sa.Column('quality_score', sa.Numeric(precision=8, scale=4), nullable=False, comment='质量评分（0~100）'),
    sa.Column('delivery_score', sa.Numeric(precision=8, scale=4), nullable=False, comment='交期评分（0~100）'),
    sa.Column('price_score', sa.Numeric(precision=8, scale=4), nullable=False, comment='价格评分（0~100）'),
    sa.Column('total_score', sa.Numeric(precision=8, scale=4), nullable=False, comment='综合评分'),
    sa.Column('evaluator_id', sa.BigInteger(), nullable=True, comment='评价人（sys_personnel.id）'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint('delivery_score >= 0 AND delivery_score <= 100', name='ck_pur_eval_delivery'),
    sa.CheckConstraint('price_score >= 0 AND price_score <= 100', name='ck_pur_eval_price'),
    sa.CheckConstraint('quality_score >= 0 AND quality_score <= 100', name='ck_pur_eval_quality'),
    sa.ForeignKeyConstraint(['evaluator_id'], ['sys_personnel.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['pur_supplier.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pur_supplier_evaluation_supplier_id'), 'pur_supplier_evaluation', ['supplier_id'], unique=False)
    op.create_table('sal_order',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=False, comment='销售订单号'),
    sa.Column('customer_id', sa.BigInteger(), nullable=False, comment='客户ID'),
    sa.Column('order_date', sa.Date(), nullable=False, comment='订单日期'),
    sa.Column('delivery_date', sa.Date(), nullable=False, comment='要求交货日期'),
    sa.Column('salesperson_id', sa.BigInteger(), nullable=True, comment='销售员（sys_personnel.id）'),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False, comment='订单总金额'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('DRAFT','CONFIRMED','RELEASED','IN_PROGRESS','COMPLETED','CANCELLED')", name='ck_sal_order_status'),
    sa.ForeignKeyConstraint(['customer_id'], ['sal_customer.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['salesperson_id'], ['sys_personnel.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_index(op.f('ix_sal_order_customer_id'), 'sal_order', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sal_order_salesperson_id'), 'sal_order', ['salesperson_id'], unique=False)
    op.create_index(op.f('ix_sal_order_status'), 'sal_order', ['status'], unique=False)
    op.create_table('sys_bom_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('bom_id', sa.BigInteger(), nullable=False, comment='BOM头ID'),
    sa.Column('material_id', sa.BigInteger(), nullable=False, comment='子件物料ID（sys_material.id）'),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='单位用量'),
    sa.Column('scrap_rate', sa.Numeric(precision=8, scale=4), nullable=False, comment='损耗率（0~1）'),
    sa.Column('sequence_no', sa.Integer(), nullable=False, comment='序号'),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint('quantity > 0', name='ck_sys_bom_item_qty'),
    sa.CheckConstraint('scrap_rate >= 0 AND scrap_rate < 1', name='ck_sys_bom_item_scrap'),
    sa.ForeignKeyConstraint(['bom_id'], ['sys_bom.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['sys_material.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bom_id', 'material_id', name='uq_sys_bom_item')
    )
    op.create_index(op.f('ix_sys_bom_item_bom_id'), 'sys_bom_item', ['bom_id'], unique=False)
    op.create_index(op.f('ix_sys_bom_item_material_id'), 'sys_bom_item', ['material_id'], unique=False)
    op.create_table('sys_routing_operation',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('routing_id', sa.BigInteger(), nullable=False, comment='工艺路线ID'),
    sa.Column('sequence_no', sa.Integer(), nullable=False, comment='工序顺序号'),
    sa.Column('operation_code', sa.String(length=50), nullable=False, comment='工序编码'),
    sa.Column('operation_name', sa.String(length=100), nullable=False, comment='工序名称'),
    sa.Column('work_center', sa.String(length=50), nullable=True, comment='工作中心'),
    sa.Column('setup_time', sa.Numeric(precision=18, scale=4), nullable=False, comment='准备工时（分钟）'),
    sa.Column('run_time', sa.Numeric(precision=18, scale=4), nullable=False, comment='单件加工工时（分钟）'),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint('run_time >= 0', name='ck_sys_routing_op_run'),
    sa.CheckConstraint('setup_time >= 0', name='ck_sys_routing_op_setup'),
    sa.ForeignKeyConstraint(['routing_id'], ['sys_routing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('routing_id', 'sequence_no', name='uq_sys_routing_operation_seq')
    )
    op.create_index(op.f('ix_sys_routing_operation_routing_id'), 'sys_routing_operation', ['routing_id'], unique=False)
    op.create_table('sys_user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='登录名'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('display_name', sa.String(length=100), nullable=False, comment='显示名'),
    sa.Column('personnel_id', sa.BigInteger(), nullable=True, comment='关联员工ID（1:1，可为空）'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最近登录时间'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('ACTIVE','INACTIVE')", name='ck_sys_user_status'),
    sa.ForeignKeyConstraint(['personnel_id'], ['sys_personnel.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('personnel_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('inv_location',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('location_code', sa.String(length=50), nullable=False, comment='库位编码'),
    sa.Column('location_name', sa.String(length=100), nullable=False, comment='库位名称'),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False, comment='仓库ID'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('ACTIVE','INACTIVE')", name='ck_inv_location_status'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inv_warehouse.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'location_code', name='uq_inv_location')
    )
    op.create_index(op.f('ix_inv_location_warehouse_id'), 'inv_location', ['warehouse_id'], unique=False)
    op.create_table('inv_reorder_rule',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.BigInteger(), nullable=False, comment='物料ID'),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False, comment='仓库ID'),
    sa.Column('reorder_point', sa.Numeric(precision=18, scale=4), nullable=False, comment='订货点'),
    sa.Column('reorder_quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='建议订货量'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('ACTIVE','INACTIVE')", name='ck_inv_reorder_rule_status'),
    sa.CheckConstraint('reorder_point >= 0', name='ck_inv_reorder_point'),
    sa.CheckConstraint('reorder_quantity >= 0', name='ck_inv_reorder_qty'),
    sa.ForeignKeyConstraint(['material_id'], ['sys_material.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inv_warehouse.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'warehouse_id', name='uq_inv_reorder_rule')
    )
    op.create_index(op.f('ix_inv_reorder_rule_material_id'), 'inv_reorder_rule', ['material_id'], unique=False)
    op.create_index(op.f('ix_inv_reorder_rule_warehouse_id'), 'inv_reorder_rule', ['warehouse_id'], unique=False)
    op.create_table('inv_replenishment_request',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_no', sa.String(length=50), nullable=False, comment='补库需求单号'),
    sa.Column('material_id', sa.BigInteger(), nullable=False, comment='物料ID'),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False, comment='仓库ID'),
    sa.Column('request_qty', sa.Numeric(precision=18, scale=4), nullable=False, comment='补库数量'),
    sa.Column('current_qty', sa.Numeric(precision=18, scale=4), nullable=False, comment='触发时库存量'),
    sa.Column('required_date', sa.Date(), nullable=False, comment='需求日期'),
    sa.Column('source_type', sa.String(length=20), nullable=False, comment='来源 REORDER/PRODUCTION'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('handled_module', sa.String(length=20), nullable=True, comment='受理模块'),
    sa.Column('handled_ref_id', sa.BigInteger(), nullable=True, comment='受理单据ID'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("source_type IN ('REORDER','PRODUCTION')", name='ck_inv_repl_source_type'),
    sa.CheckConstraint("status IN ('DRAFT','CONFIRMED','RELEASED','COMPLETED','CANCELLED')", name='ck_inv_repl_status'),
    sa.CheckConstraint('request_qty > 0', name='ck_inv_repl_qty'),
    sa.ForeignKeyConstraint(['material_id'], ['sys_material.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inv_warehouse.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_no')
    )
    op.create_index(op.f('ix_inv_replenishment_request_material_id'), 'inv_replenishment_request', ['material_id'], unique=False)
    op.create_index(op.f('ix_inv_replenishment_request_source_type'), 'inv_replenishment_request', ['source_type'], unique=False)
    op.create_index(op.f('ix_inv_replenishment_request_status'), 'inv_replenishment_request', ['status'], unique=False)
    op.create_table('inv_stocktake',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stocktake_no', sa.String(length=50), nullable=False, comment='盘点单号'),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False, comment='仓库ID'),
    sa.Column('stocktake_date', sa.Date(), nullable=False, comment='盘点日期'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('DRAFT','CONFIRMED','COMPLETED','CANCELLED')", name='ck_inv_stocktake_status'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inv_warehouse.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stocktake_no')
    )
    op.create_table('inv_transfer',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('transfer_no', sa.String(length=50), nullable=False, comment='移库单号'),
    sa.Column('from_warehouse_id', sa.BigInteger(), nullable=False, comment='源仓库ID'),
    sa.Column('to_warehouse_id', sa.BigInteger(), nullable=False, comment='目标仓库ID'),
    sa.Column('transfer_date', sa.Date(), nullable=False, comment='移库日期'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('DRAFT','CONFIRMED','COMPLETED','CANCELLED')", name='ck_inv_transfer_status'),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['inv_warehouse.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['inv_warehouse.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transfer_no')
    )
    op.create_table('pln_production_plan',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('plan_no', sa.String(length=50), nullable=False, comment='作业计划编号'),
    sa.Column('mrp_result_id', sa.BigInteger(), nullable=True, comment='MRP结果ID'),
    sa.Column('source_type', sa.String(length=20), nullable=False, comment='来源 MRP/REPLENISHMENT/MANUAL'),
    sa.Column('source_reference_id', sa.Integer(), nullable=True, comment='来源单据ID（多态引用）'),
    sa.Column('material_id', sa.BigInteger(), nullable=False, comment='自制件物料ID'),
    sa.Column('planned_qty', sa.Numeric(precision=18, scale=4), nullable=False, comment='计划生产数量'),
    sa.Column('completed_qty', sa.Numeric(precision=18, scale=4), nullable=False, comment='已完工数量'),
    sa.Column('plan_date', sa.Date(), nullable=False, comment='计划日期'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='计划开始日期'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='计划完成日期'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("source_type IN ('MRP','REPLENISHMENT','MANUAL')", name='ck_pln_production_plan_source'),
    sa.CheckConstraint("status IN ('DRAFT','CONFIRMED','RELEASED','IN_PROGRESS','COMPLETED','CANCELLED')", name='ck_pln_production_plan_status'),
    sa.CheckConstraint('completed_qty >= 0', name='ck_pln_production_plan_completed'),
    sa.CheckConstraint('planned_qty > 0', name='ck_pln_production_plan_qty'),
    sa.ForeignKeyConstraint(['material_id'], ['sys_material.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['mrp_result_id'], ['pln_mrp_result.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_no')
    )
    op.create_index(op.f('ix_pln_production_plan_material_id'), 'pln_production_plan', ['material_id'], unique=False)
    op.create_index(op.f('ix_pln_production_plan_mrp_result_id'), 'pln_production_plan', ['mrp_result_id'], unique=False)
    op.create_index(op.f('ix_pln_production_plan_status'), 'pln_production_plan', ['status'], unique=False)
    op.create_table('pur_order_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False, comment='订单头ID'),
    sa.Column('line_no', sa.Integer(), nullable=False, comment='行号'),
    sa.Column('material_id', sa.BigInteger(), nullable=False, comment='物料ID'),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='采购数量'),
    sa.Column('received_qty', sa.Numeric(precision=18, scale=4), nullable=False, comment='已到货数量'),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False, comment='单价'),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False, comment='金额'),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint('quantity > 0', name='ck_pur_order_item_qty'),
    sa.CheckConstraint('received_qty >= 0', name='ck_pur_order_item_received'),
    sa.ForeignKeyConstraint(['material_id'], ['sys_material.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['pur_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'line_no', name='uq_pur_order_item_line')
    )
    op.create_index(op.f('ix_pur_order_item_material_id'), 'pur_order_item', ['material_id'], unique=False)
    op.create_index(op.f('ix_pur_order_item_order_id'), 'pur_order_item', ['order_id'], unique=False)
    op.create_table('pur_receipt',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('receipt_no', sa.String(length=50), nullable=False, comment='到货单号'),
    sa.Column('purchase_order_id', sa.BigInteger(), nullable=False, comment='采购订单ID'),
    sa.Column('supplier_id', sa.BigInteger(), nullable=False, comment='供应商ID'),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False, comment='收货仓库ID'),
    sa.Column('receipt_date', sa.Date(), nullable=False, comment='到货日期'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('DRAFT','CONFIRMED','COMPLETED','CANCELLED')", name='ck_pur_receipt_status'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['pur_order.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['pur_supplier.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inv_warehouse.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_no')
    )
    op.create_index(op.f('ix_pur_receipt_purchase_order_id'), 'pur_receipt', ['purchase_order_id'], unique=False)
    op.create_index(op.f('ix_pur_receipt_status'), 'pur_receipt', ['status'], unique=False)
    op.create_index(op.f('ix_pur_receipt_supplier_id'), 'pur_receipt', ['supplier_id'], unique=False)
    op.create_table('sal_order_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False, comment='订单头ID'),
    sa.Column('line_no', sa.Integer(), nullable=False, comment='行号'),
    sa.Column('material_id', sa.BigInteger(), nullable=False, comment='物料ID'),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='订单数量'),
    sa.Column('delivered_qty', sa.Numeric(precision=18, scale=4), nullable=False, comment='已发货数量'),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False, comment='单价'),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False, comment='金额'),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint('delivered_qty >= 0', name='ck_sal_order_item_delivered'),
    sa.CheckConstraint('quantity > 0', name='ck_sal_order_item_qty'),
    sa.ForeignKeyConstraint(['material_id'], ['sys_material.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['sal_order.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'line_no', name='uq_sal_order_item_line')
    )
    op.create_index(op.f('ix_sal_order_item_material_id'), 'sal_order_item', ['material_id'], unique=False)
    op.create_index(op.f('ix_sal_order_item_order_id'), 'sal_order_item', ['order_id'], unique=False)
    op.create_table('sal_return',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('return_no', sa.String(length=50), nullable=False, comment='退货单号'),
    sa.Column('order_id', sa.BigInteger(), nullable=True, comment='原销售订单ID'),
    sa.Column('customer_id', sa.BigInteger(), nullable=False, comment='客户ID'),
    sa.Column('return_date', sa.Date(), nullable=False, comment='退货日期'),
    sa.Column('reason', sa.String(length=200), nullable=True, comment='退货原因'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('DRAFT','CONFIRMED','COMPLETED','CANCELLED')", name='ck_sal_return_status'),
    sa.ForeignKeyConstraint(['customer_id'], ['sal_customer.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['sal_order.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('return_no')
    )
    op.create_index(op.f('ix_sal_return_customer_id'), 'sal_return', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sal_return_order_id'), 'sal_return', ['order_id'], unique=False)
    op.create_index(op.f('ix_sal_return_status'), 'sal_return', ['status'], unique=False)
    op.create_table('sal_shipment',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('shipment_no', sa.String(length=50), nullable=False, comment='发货单号'),
    sa.Column('order_id', sa.BigInteger(), nullable=False, comment='销售订单ID'),
    sa.Column('customer_id', sa.BigInteger(), nullable=False, comment='客户ID'),
    sa.Column('shipment_date', sa.Date(), nullable=False, comment='发货日期'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('DRAFT','CONFIRMED','COMPLETED','CANCELLED')", name='ck_sal_shipment_status'),
    sa.ForeignKeyConstraint(['customer_id'], ['sal_customer.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['sal_order.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_no')
    )
    op.create_index(op.f('ix_sal_shipment_customer_id'), 'sal_shipment', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sal_shipment_order_id'), 'sal_shipment', ['order_id'], unique=False)
    op.create_index(op.f('ix_sal_shipment_status'), 'sal_shipment', ['status'], unique=False)
    op.create_table('sys_user_role',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.ForeignKeyConstraint(['role_id'], ['sys_role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_sys_user_role')
    )
    op.create_index(op.f('ix_sys_user_role_role_id'), 'sys_user_role', ['role_id'], unique=False)
    op.create_index(op.f('ix_sys_user_role_user_id'), 'sys_user_role', ['user_id'], unique=False)
    op.create_table('inv_balance',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False, comment='仓库ID'),
    sa.Column('location_id', sa.BigInteger(), nullable=True, comment='库位ID'),
    sa.Column('material_id', sa.BigInteger(), nullable=False, comment='物料ID'),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='库存数量'),
    sa.Column('locked_quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='锁定量（已分配未出库）'),
    sa.Column('updated_at_txn', sa.DateTime(), nullable=True, comment='最近一次变动时间'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint('locked_quantity >= 0', name='ck_inv_balance_locked'),
    sa.CheckConstraint('quantity >= 0', name='ck_inv_balance_qty'),
    sa.ForeignKeyConstraint(['location_id'], ['inv_location.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['material_id'], ['sys_material.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inv_warehouse.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'location_id', 'material_id', name='uq_inv_balance_bucket')
    )
    op.create_index(op.f('ix_inv_balance_location_id'), 'inv_balance', ['location_id'], unique=False)
    op.create_index(op.f('ix_inv_balance_material_id'), 'inv_balance', ['material_id'], unique=False)
    op.create_index(op.f('ix_inv_balance_warehouse_id'), 'inv_balance', ['warehouse_id'], unique=False)
    op.create_table('inv_stocktake_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stocktake_id', sa.BigInteger(), nullable=False, comment='盘点单头ID'),
    sa.Column('material_id', sa.BigInteger(), nullable=False, comment='物料ID'),
    sa.Column('location_id', sa.BigInteger(), nullable=True, comment='库位ID'),
    sa.Column('book_qty', sa.Numeric(precision=18, scale=4), nullable=False, comment='账面数量'),
    sa.Column('actual_qty', sa.Numeric(precision=18, scale=4), nullable=False, comment='实盘数量'),
    sa.Column('difference', sa.Numeric(precision=18, scale=4), nullable=False, comment='差异数量'),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint('actual_qty >= 0', name='ck_inv_stocktake_actual'),
    sa.ForeignKeyConstraint(['location_id'], ['inv_location.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['material_id'], ['sys_material.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stocktake_id'], ['inv_stocktake.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inv_stocktake_item_stocktake_id'), 'inv_stocktake_item', ['stocktake_id'], unique=False)
    op.create_table('inv_transaction',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('transaction_no', sa.String(length=50), nullable=False, comment='流水单号'),
    sa.Column('transaction_type', sa.String(length=20), nullable=False, comment='类型 IN/OUT/TRANSFER_IN/TRANSFER_OUT/ADJUST'),
    sa.Column('material_id', sa.BigInteger(), nullable=False, comment='物料ID'),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False, comment='仓库ID'),
    sa.Column('location_id', sa.BigInteger(), nullable=True, comment='库位ID'),
    sa.Column('quantity_change', sa.Numeric(precision=18, scale=4), nullable=False, comment='变动数量（入库为正，出库为负）'),
    sa.Column('quantity_after', sa.Numeric(precision=18, scale=4), nullable=False, comment='变动后结存'),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=2), nullable=False, comment='单位成本'),
    sa.Column('biz_date', sa.Date(), nullable=False, comment='业务日期'),
    sa.Column('source_module', sa.String(length=20), nullable=False, comment='来源模块'),
    sa.Column('source_type', sa.String(length=30), nullable=False, comment='来源业务类型（PURCHASE_RECEIPT 等）'),
    sa.Column('source_reference_id', sa.BigInteger(), nullable=True, comment='来源单据ID'),
    sa.Column('source_no', sa.String(length=50), nullable=True, comment='来源单号（冗余便于查询）'),
    sa.Column('operator_id', sa.BigInteger(), nullable=True, comment='操作人ID（sys_user.id）'),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("source_type IN ('PURCHASE_RECEIPT','PRODUCTION_COMPLETION','MATERIAL_REQUISITION','SALES_SHIPMENT','SALES_RETURN','TRANSFER','STOCKTAKE','MANUAL')", name='ck_inv_transaction_source_type'),
    sa.CheckConstraint("transaction_type IN ('IN','OUT','TRANSFER_IN','TRANSFER_OUT','ADJUST')", name='ck_inv_transaction_type'),
    sa.ForeignKeyConstraint(['location_id'], ['inv_location.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['material_id'], ['sys_material.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inv_warehouse.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_no')
    )
    op.create_index(op.f('ix_inv_transaction_material_id'), 'inv_transaction', ['material_id'], unique=False)
    op.create_index(op.f('ix_inv_transaction_source_reference_id'), 'inv_transaction', ['source_reference_id'], unique=False)
    op.create_index(op.f('ix_inv_transaction_transaction_type'), 'inv_transaction', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_inv_transaction_warehouse_id'), 'inv_transaction', ['warehouse_id'], unique=False)
    op.create_table('inv_transfer_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('transfer_id', sa.BigInteger(), nullable=False, comment='移库单头ID'),
    sa.Column('material_id', sa.BigInteger(), nullable=False, comment='物料ID'),
    sa.Column('from_location_id', sa.BigInteger(), nullable=True, comment='源库位ID'),
    sa.Column('to_location_id', sa.BigInteger(), nullable=True, comment='目标库位ID'),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='移库数量'),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint('quantity > 0', name='ck_inv_transfer_item_qty'),
    sa.ForeignKeyConstraint(['from_location_id'], ['inv_location.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['material_id'], ['sys_material.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_location_id'], ['inv_location.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transfer_id'], ['inv_transfer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inv_transfer_item_transfer_id'), 'inv_transfer_item', ['transfer_id'], unique=False)
    op.create_table('pln_dispatch_order',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dispatch_no', sa.String(length=50), nullable=False, comment='派工单号'),
    sa.Column('plan_id', sa.BigInteger(), nullable=True, comment='生产作业计划ID'),
    sa.Column('operation', sa.String(length=60), nullable=True, comment='工序'),
    sa.Column('planned_qty', sa.Numeric(precision=18, scale=4), nullable=False, comment='派工数量'),
    sa.Column('completed_qty', sa.Numeric(precision=18, scale=4), nullable=False, comment='完成数量'),
    sa.Column('worker_id', sa.BigInteger(), nullable=True, comment='作业人员（sys_personnel.id）'),
    sa.Column('planned_start', sa.Date(), nullable=False, comment='计划开始日期'),
    sa.Column('planned_end', sa.Date(), nullable=False, comment='计划结束日期'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('DRAFT','CONFIRMED','RELEASED','IN_PROGRESS','COMPLETED','CANCELLED')", name='ck_pln_dispatch_status'),
    sa.CheckConstraint('completed_qty >= 0', name='ck_pln_dispatch_completed'),
    sa.CheckConstraint('planned_qty > 0', name='ck_pln_dispatch_qty'),
    sa.ForeignKeyConstraint(['plan_id'], ['pln_production_plan.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['worker_id'], ['sys_personnel.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dispatch_no')
    )
    op.create_index(op.f('ix_pln_dispatch_order_plan_id'), 'pln_dispatch_order', ['plan_id'], unique=False)
    op.create_index(op.f('ix_pln_dispatch_order_status'), 'pln_dispatch_order', ['status'], unique=False)
    op.create_index(op.f('ix_pln_dispatch_order_worker_id'), 'pln_dispatch_order', ['worker_id'], unique=False)
    op.create_table('pln_material_requisition',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('req_no', sa.String(length=50), nullable=False, comment='领料单号'),
    sa.Column('plan_id', sa.BigInteger(), nullable=True, comment='生产作业计划ID'),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=True, comment='领料仓库ID'),
    sa.Column('req_date', sa.Date(), nullable=False, comment='领料日期'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('DRAFT','CONFIRMED','RELEASED','IN_PROGRESS','COMPLETED','CANCELLED')", name='ck_pln_requisition_status'),
    sa.ForeignKeyConstraint(['plan_id'], ['pln_production_plan.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inv_warehouse.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('req_no')
    )
    op.create_index(op.f('ix_pln_material_requisition_plan_id'), 'pln_material_requisition', ['plan_id'], unique=False)
    op.create_index(op.f('ix_pln_material_requisition_status'), 'pln_material_requisition', ['status'], unique=False)
    op.create_table('pur_receipt_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('receipt_id', sa.BigInteger(), nullable=False, comment='到货单头ID'),
    sa.Column('order_item_id', sa.BigInteger(), nullable=False, comment='采购订单行ID'),
    sa.Column('material_id', sa.BigInteger(), nullable=False, comment='物料ID'),
    sa.Column('location_id', sa.BigInteger(), nullable=True, comment='收货库位ID'),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='到货数量'),
    sa.Column('qualified_qty', sa.Numeric(precision=18, scale=4), nullable=False, comment='合格数量'),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint('qualified_qty >= 0', name='ck_pur_receipt_item_qualified'),
    sa.CheckConstraint('quantity > 0', name='ck_pur_receipt_item_qty'),
    sa.ForeignKeyConstraint(['location_id'], ['inv_location.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['material_id'], ['sys_material.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_item_id'], ['pur_order_item.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receipt_id'], ['pur_receipt.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pur_receipt_item_material_id'), 'pur_receipt_item', ['material_id'], unique=False)
    op.create_index(op.f('ix_pur_receipt_item_order_item_id'), 'pur_receipt_item', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_pur_receipt_item_receipt_id'), 'pur_receipt_item', ['receipt_id'], unique=False)
    op.create_table('sal_return_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('return_id', sa.BigInteger(), nullable=False, comment='退货单头ID'),
    sa.Column('material_id', sa.BigInteger(), nullable=False, comment='物料ID'),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False, comment='退回仓库ID'),
    sa.Column('location_id', sa.BigInteger(), nullable=True, comment='退回库位ID'),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='退货数量'),
    sa.Column('reason', sa.String(length=200), nullable=True, comment='行退货原因'),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint('quantity > 0', name='ck_sal_return_item_qty'),
    sa.ForeignKeyConstraint(['location_id'], ['inv_location.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['material_id'], ['sys_material.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['return_id'], ['sal_return.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inv_warehouse.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sal_return_item_material_id'), 'sal_return_item', ['material_id'], unique=False)
    op.create_index(op.f('ix_sal_return_item_return_id'), 'sal_return_item', ['return_id'], unique=False)
    op.create_table('sal_shipment_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('shipment_id', sa.BigInteger(), nullable=False, comment='发货单头ID'),
    sa.Column('order_item_id', sa.BigInteger(), nullable=False, comment='销售订单行ID'),
    sa.Column('material_id', sa.BigInteger(), nullable=False, comment='物料ID'),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False, comment='发货仓库ID'),
    sa.Column('location_id', sa.BigInteger(), nullable=True, comment='发货库位ID'),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='发货数量'),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint('quantity > 0', name='ck_sal_shipment_item_qty'),
    sa.ForeignKeyConstraint(['location_id'], ['inv_location.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['material_id'], ['sys_material.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_item_id'], ['sal_order_item.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shipment_id'], ['sal_shipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inv_warehouse.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sal_shipment_item_material_id'), 'sal_shipment_item', ['material_id'], unique=False)
    op.create_index(op.f('ix_sal_shipment_item_order_item_id'), 'sal_shipment_item', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_sal_shipment_item_shipment_id'), 'sal_shipment_item', ['shipment_id'], unique=False)
    op.create_table('pln_completion_report',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('report_no', sa.String(length=50), nullable=False, comment='完工报告单号'),
    sa.Column('plan_id', sa.BigInteger(), nullable=True, comment='生产作业计划ID'),
    sa.Column('dispatch_id', sa.BigInteger(), nullable=True, comment='派工单ID'),
    sa.Column('material_id', sa.BigInteger(), nullable=False, comment='产出物料ID'),
    sa.Column('completed_qty', sa.Numeric(precision=18, scale=4), nullable=False, comment='完工数量'),
    sa.Column('qualified_qty', sa.Numeric(precision=18, scale=4), nullable=False, comment='合格数量（入库数量）'),
    sa.Column('scrap_qty', sa.Numeric(precision=18, scale=4), nullable=False, comment='报废数量'),
    sa.Column('warehouse_id', sa.BigInteger(), nullable=False, comment='入库仓库ID'),
    sa.Column('location_id', sa.BigInteger(), nullable=True, comment='入库库位ID'),
    sa.Column('report_date', sa.Date(), nullable=False, comment='报工日期'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint("status IN ('DRAFT','CONFIRMED','COMPLETED','CANCELLED')", name='ck_pln_completion_status'),
    sa.CheckConstraint('completed_qty > 0', name='ck_pln_completion_qty'),
    sa.CheckConstraint('qualified_qty >= 0', name='ck_pln_completion_qualified'),
    sa.CheckConstraint('scrap_qty >= 0', name='ck_pln_completion_scrap'),
    sa.ForeignKeyConstraint(['dispatch_id'], ['pln_dispatch_order.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['inv_location.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['material_id'], ['sys_material.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_id'], ['pln_production_plan.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['inv_warehouse.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_no')
    )
    op.create_index(op.f('ix_pln_completion_report_material_id'), 'pln_completion_report', ['material_id'], unique=False)
    op.create_index(op.f('ix_pln_completion_report_plan_id'), 'pln_completion_report', ['plan_id'], unique=False)
    op.create_index(op.f('ix_pln_completion_report_status'), 'pln_completion_report', ['status'], unique=False)
    op.create_table('pln_material_requisition_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('requisition_id', sa.BigInteger(), nullable=False, comment='领料单头ID'),
    sa.Column('material_id', sa.BigInteger(), nullable=False, comment='物料ID'),
    sa.Column('required_qty', sa.Numeric(precision=18, scale=4), nullable=False, comment='需求数量'),
    sa.Column('issued_qty', sa.Numeric(precision=18, scale=4), nullable=False, comment='已领数量'),
    sa.Column('location_id', sa.BigInteger(), nullable=True, comment='领料库位ID'),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='备注'),
    sa.Column('created_by', sa.BigInteger(), nullable=True, comment='创建人ID（sys_user.id）'),
    sa.Column('updated_by', sa.BigInteger(), nullable=True, comment='更新人ID（sys_user.id）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.CheckConstraint('issued_qty >= 0', name='ck_pln_req_item_issued'),
    sa.CheckConstraint('required_qty > 0', name='ck_pln_req_item_required'),
    sa.ForeignKeyConstraint(['location_id'], ['inv_location.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['material_id'], ['sys_material.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requisition_id'], ['pln_material_requisition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pln_material_requisition_item_material_id'), 'pln_material_requisition_item', ['material_id'], unique=False)
    op.create_index(op.f('ix_pln_material_requisition_item_requisition_id'), 'pln_material_requisition_item', ['requisition_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pln_material_requisition_item_requisition_id'), table_name='pln_material_requisition_item')
    op.drop_index(op.f('ix_pln_material_requisition_item_material_id'), table_name='pln_material_requisition_item')
    op.drop_table('pln_material_requisition_item')
    op.drop_index(op.f('ix_pln_completion_report_status'), table_name='pln_completion_report')
    op.drop_index(op.f('ix_pln_completion_report_plan_id'), table_name='pln_completion_report')
    op.drop_index(op.f('ix_pln_completion_report_material_id'), table_name='pln_completion_report')
    op.drop_table('pln_completion_report')
    op.drop_index(op.f('ix_sal_shipment_item_shipment_id'), table_name='sal_shipment_item')
    op.drop_index(op.f('ix_sal_shipment_item_order_item_id'), table_name='sal_shipment_item')
    op.drop_index(op.f('ix_sal_shipment_item_material_id'), table_name='sal_shipment_item')
    op.drop_table('sal_shipment_item')
    op.drop_index(op.f('ix_sal_return_item_return_id'), table_name='sal_return_item')
    op.drop_index(op.f('ix_sal_return_item_material_id'), table_name='sal_return_item')
    op.drop_table('sal_return_item')
    op.drop_index(op.f('ix_pur_receipt_item_receipt_id'), table_name='pur_receipt_item')
    op.drop_index(op.f('ix_pur_receipt_item_order_item_id'), table_name='pur_receipt_item')
    op.drop_index(op.f('ix_pur_receipt_item_material_id'), table_name='pur_receipt_item')
    op.drop_table('pur_receipt_item')
    op.drop_index(op.f('ix_pln_material_requisition_status'), table_name='pln_material_requisition')
    op.drop_index(op.f('ix_pln_material_requisition_plan_id'), table_name='pln_material_requisition')
    op.drop_table('pln_material_requisition')
    op.drop_index(op.f('ix_pln_dispatch_order_worker_id'), table_name='pln_dispatch_order')
    op.drop_index(op.f('ix_pln_dispatch_order_status'), table_name='pln_dispatch_order')
    op.drop_index(op.f('ix_pln_dispatch_order_plan_id'), table_name='pln_dispatch_order')
    op.drop_table('pln_dispatch_order')
    op.drop_index(op.f('ix_inv_transfer_item_transfer_id'), table_name='inv_transfer_item')
    op.drop_table('inv_transfer_item')
    op.drop_index(op.f('ix_inv_transaction_warehouse_id'), table_name='inv_transaction')
    op.drop_index(op.f('ix_inv_transaction_transaction_type'), table_name='inv_transaction')
    op.drop_index(op.f('ix_inv_transaction_source_reference_id'), table_name='inv_transaction')
    op.drop_index(op.f('ix_inv_transaction_material_id'), table_name='inv_transaction')
    op.drop_table('inv_transaction')
    op.drop_index(op.f('ix_inv_stocktake_item_stocktake_id'), table_name='inv_stocktake_item')
    op.drop_table('inv_stocktake_item')
    op.drop_index(op.f('ix_inv_balance_warehouse_id'), table_name='inv_balance')
    op.drop_index(op.f('ix_inv_balance_material_id'), table_name='inv_balance')
    op.drop_index(op.f('ix_inv_balance_location_id'), table_name='inv_balance')
    op.drop_table('inv_balance')
    op.drop_index(op.f('ix_sys_user_role_user_id'), table_name='sys_user_role')
    op.drop_index(op.f('ix_sys_user_role_role_id'), table_name='sys_user_role')
    op.drop_table('sys_user_role')
    op.drop_index(op.f('ix_sal_shipment_status'), table_name='sal_shipment')
    op.drop_index(op.f('ix_sal_shipment_order_id'), table_name='sal_shipment')
    op.drop_index(op.f('ix_sal_shipment_customer_id'), table_name='sal_shipment')
    op.drop_table('sal_shipment')
    op.drop_index(op.f('ix_sal_return_status'), table_name='sal_return')
    op.drop_index(op.f('ix_sal_return_order_id'), table_name='sal_return')
    op.drop_index(op.f('ix_sal_return_customer_id'), table_name='sal_return')
    op.drop_table('sal_return')
    op.drop_index(op.f('ix_sal_order_item_order_id'), table_name='sal_order_item')
    op.drop_index(op.f('ix_sal_order_item_material_id'), table_name='sal_order_item')
    op.drop_table('sal_order_item')
    op.drop_index(op.f('ix_pur_receipt_supplier_id'), table_name='pur_receipt')
    op.drop_index(op.f('ix_pur_receipt_status'), table_name='pur_receipt')
    op.drop_index(op.f('ix_pur_receipt_purchase_order_id'), table_name='pur_receipt')
    op.drop_table('pur_receipt')
    op.drop_index(op.f('ix_pur_order_item_order_id'), table_name='pur_order_item')
    op.drop_index(op.f('ix_pur_order_item_material_id'), table_name='pur_order_item')
    op.drop_table('pur_order_item')
    op.drop_index(op.f('ix_pln_production_plan_status'), table_name='pln_production_plan')
    op.drop_index(op.f('ix_pln_production_plan_mrp_result_id'), table_name='pln_production_plan')
    op.drop_index(op.f('ix_pln_production_plan_material_id'), table_name='pln_production_plan')
    op.drop_table('pln_production_plan')
    op.drop_table('inv_transfer')
    op.drop_table('inv_stocktake')
    op.drop_index(op.f('ix_inv_replenishment_request_status'), table_name='inv_replenishment_request')
    op.drop_index(op.f('ix_inv_replenishment_request_source_type'), table_name='inv_replenishment_request')
    op.drop_index(op.f('ix_inv_replenishment_request_material_id'), table_name='inv_replenishment_request')
    op.drop_table('inv_replenishment_request')
    op.drop_index(op.f('ix_inv_reorder_rule_warehouse_id'), table_name='inv_reorder_rule')
    op.drop_index(op.f('ix_inv_reorder_rule_material_id'), table_name='inv_reorder_rule')
    op.drop_table('inv_reorder_rule')
    op.drop_index(op.f('ix_inv_location_warehouse_id'), table_name='inv_location')
    op.drop_table('inv_location')
    op.drop_table('sys_user')
    op.drop_index(op.f('ix_sys_routing_operation_routing_id'), table_name='sys_routing_operation')
    op.drop_table('sys_routing_operation')
    op.drop_index(op.f('ix_sys_bom_item_material_id'), table_name='sys_bom_item')
    op.drop_index(op.f('ix_sys_bom_item_bom_id'), table_name='sys_bom_item')
    op.drop_table('sys_bom_item')
    op.drop_index(op.f('ix_sal_order_status'), table_name='sal_order')
    op.drop_index(op.f('ix_sal_order_salesperson_id'), table_name='sal_order')
    op.drop_index(op.f('ix_sal_order_customer_id'), table_name='sal_order')
    op.drop_table('sal_order')
    op.drop_index(op.f('ix_pur_supplier_evaluation_supplier_id'), table_name='pur_supplier_evaluation')
    op.drop_table('pur_supplier_evaluation')
    op.drop_index(op.f('ix_pur_order_supplier_id'), table_name='pur_order')
    op.drop_index(op.f('ix_pur_order_status'), table_name='pur_order')
    op.drop_index(op.f('ix_pur_order_buyer_id'), table_name='pur_order')
    op.drop_table('pur_order')
    op.drop_index(op.f('ix_pln_mrp_result_supply_type'), table_name='pln_mrp_result')
    op.drop_index(op.f('ix_pln_mrp_result_status'), table_name='pln_mrp_result')
    op.drop_index(op.f('ix_pln_mrp_result_run_id'), table_name='pln_mrp_result')
    op.drop_index(op.f('ix_pln_mrp_result_parent_material_id'), table_name='pln_mrp_result')
    op.drop_index(op.f('ix_pln_mrp_result_material_id'), table_name='pln_mrp_result')
    op.drop_table('pln_mrp_result')
    op.drop_index(op.f('ix_inv_warehouse_org_id'), table_name='inv_warehouse')
    op.drop_table('inv_warehouse')
    op.drop_index(op.f('ix_sys_routing_material_id'), table_name='sys_routing')
    op.drop_table('sys_routing')
    op.drop_index(op.f('ix_sys_role_permission_role_id'), table_name='sys_role_permission')
    op.drop_index(op.f('ix_sys_role_permission_permission_id'), table_name='sys_role_permission')
    op.drop_table('sys_role_permission')
    op.drop_index(op.f('ix_sys_personnel_org_id'), table_name='sys_personnel')
    op.drop_table('sys_personnel')
    op.drop_index(op.f('ix_sys_dictionary_item_dict_id'), table_name='sys_dictionary_item')
    op.drop_table('sys_dictionary_item')
    op.drop_index(op.f('ix_sys_bom_material_id'), table_name='sys_bom')
    op.drop_table('sys_bom')
    op.drop_index(op.f('ix_sal_forecast_status'), table_name='sal_forecast')
    op.drop_index(op.f('ix_sal_forecast_material_id'), table_name='sal_forecast')
    op.drop_index(op.f('ix_sal_forecast_customer_id'), table_name='sal_forecast')
    op.drop_table('sal_forecast')
    op.drop_index(op.f('ix_pur_supplier_material_supplier_id'), table_name='pur_supplier_material')
    op.drop_index(op.f('ix_pur_supplier_material_material_id'), table_name='pur_supplier_material')
    op.drop_table('pur_supplier_material')
    op.drop_index(op.f('ix_pur_purchase_plan_item_source_type'), table_name='pur_purchase_plan_item')
    op.drop_index(op.f('ix_pur_purchase_plan_item_source_reference_id'), table_name='pur_purchase_plan_item')
    op.drop_index(op.f('ix_pur_purchase_plan_item_plan_id'), table_name='pur_purchase_plan_item')
    op.drop_index(op.f('ix_pur_purchase_plan_item_material_id'), table_name='pur_purchase_plan_item')
    op.drop_table('pur_purchase_plan_item')
    op.drop_index(op.f('ix_pln_mrp_run_status'), table_name='pln_mrp_run')
    op.drop_index(op.f('ix_pln_mrp_run_mps_id'), table_name='pln_mrp_run')
    op.drop_table('pln_mrp_run')
    op.drop_index(op.f('ix_pln_mps_item_mps_id'), table_name='pln_mps_item')
    op.drop_index(op.f('ix_pln_mps_item_material_id'), table_name='pln_mps_item')
    op.drop_table('pln_mps_item')
    op.drop_index(op.f('ix_pln_demand_status'), table_name='pln_demand')
    op.drop_index(op.f('ix_pln_demand_source_type'), table_name='pln_demand')
    op.drop_index(op.f('ix_pln_demand_source_reference_id'), table_name='pln_demand')
    op.drop_index(op.f('ix_pln_demand_material_id'), table_name='pln_demand')
    op.drop_index(op.f('ix_pln_demand_due_date'), table_name='pln_demand')
    op.drop_table('pln_demand')
    op.drop_table('sys_role')
    op.drop_index(op.f('ix_sys_permission_parent_id'), table_name='sys_permission')
    op.drop_table('sys_permission')
    op.drop_index(op.f('ix_sys_organization_parent_id'), table_name='sys_organization')
    op.drop_table('sys_organization')
    op.drop_index(op.f('ix_sys_operation_log_module'), table_name='sys_operation_log')
    op.drop_table('sys_operation_log')
    op.drop_index(op.f('ix_sys_material_supply_type'), table_name='sys_material')
    op.drop_index(op.f('ix_sys_material_material_type'), table_name='sys_material')
    op.drop_table('sys_material')
    op.drop_table('sys_dictionary')
    op.drop_table('sal_customer')
    op.drop_table('pur_supplier')
    op.drop_index(op.f('ix_pur_purchase_plan_status'), table_name='pur_purchase_plan')
    op.drop_table('pur_purchase_plan')
    op.drop_index(op.f('ix_pln_mps_status'), table_name='pln_mps')
    op.drop_table('pln_mps')
    # ### end Alembic commands ###
