"""add user approval status

Revision ID: a91a25db68da
Revises: 13b276c7702d
Create Date: 2026-09-17 16:11:18.974591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a91a25db68da'
down_revision: Union[str, None] = '13b276c7702d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. 先以可空方式加列，避免存量行被 MySQL 填成空串
    op.add_column(
        "user",
        sa.Column(
            "approval_status",
            sa.String(length=16),
            nullable=True,
            comment="注册审批状态 PENDING/APPROVED/REJECTED（管理员与存量账号默认 APPROVED）",
        ),
    )
    # 2. 存量账号（管理员创建等）一律回填为已批准
    op.execute("UPDATE `user` SET approval_status = 'APPROVED' WHERE approval_status IS NULL")
    # 3. 收紧为非空
    op.alter_column(
        "user",
        "approval_status",
        existing_type=sa.String(length=16),
        nullable=False,
        comment="注册审批状态 PENDING/APPROVED/REJECTED（管理员与存量账号默认 APPROVED）",
    )
    op.create_index(op.f("ix_user_approval_status"), "user", ["approval_status"], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_approval_status'), table_name='user')
    op.drop_column('user', 'approval_status')
    # ### end Alembic commands ###
